### ISSUE TITLE
torch._C._LinAlgError while training

### ISSUE THREAD

**Issue by mxjmtxrm** [ruikangliu/FlatQuant#5]
Hi, great work! 
When I tried to quantize my llama model, I met the following error:
```
[2024-11-04 02:04:05 root](train_utils.py 94): INFO ========= Layer 0 =========
[2024-11-04 02:04:22 root](train_utils.py 164): INFO layer 0 lwc lac iter 0, lr 0.00494542  time 10.204175s, mse: 0.00010393
[2024-11-04 02:04:31 root](train_utils.py 164): INFO layer 0 lwc lac iter 1, lr 0.00478408  time 8.453322s, mse: 0.00006361
[2024-11-04 02:04:39 root](train_utils.py 164): INFO layer 0 lwc lac iter 2, lr 0.00452302  time 8.452416s, mse: 0.00004074
[2024-11-04 02:04:48 root](train_utils.py 164): INFO layer 0 lwc lac iter 3, lr 0.00417365  time 8.596735s, mse: 0.00003601
[2024-11-04 02:04:56 root](train_utils.py 164): INFO layer 0 lwc lac iter 4, lr 0.00375125  time 8.426240s, mse: 0.00007681
Traceback (most recent call last):
  File "/workspace/FlatQuant/./main.py", line 93, in <module>
    main()
  File "/workspace/FlatQuant/./main.py", line 35, in main
    train_utils.cali_flat_quant(args, model, trainloader, utils.DEV, logger=logger)
  File "/workspace/FlatQuant/flatquant/train_utils.py", line 152, in cali_flat_quant
    quant_out = layer(fp_inps[index:index+args.cali_bsz,], attention_mask=attention_mask_batch, position_ids=position_ids,cache_position=cache_position)[0]
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/modeling_llama.py", line 763, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/FlatQuant/flatquant/model_tools/llama_utils.py", line 206, in forward
    query_states, key_states, value_states = self._trans_forward_after_ln(hidden_states)
  File "/workspace/FlatQuant/flatquant/model_tools/llama_utils.py", line 161, in _trans_forward_after_ln
    hidden_states = self.ln_trans(hidden_states)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/FlatQuant/flatquant/trans_utils.py", line 92, in forward
    matrix_u_left, matrix_u_right = self.linear_u_left.weight, self.linear_u_right.weight
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/utils/parametrize.py", line 368, in get_parametrized
    return parametrization()
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/utils/parametrize.py", line 265, in forward
    x = self[0](self.original)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/utils/parametrizations.py", line 90, in forward
    Q = torch.linalg.solve(torch.add(Id, A, alpha=-0.5), torch.add(Id, A, alpha=0.5))
torch._C._LinAlgError: torch.linalg.solve: The solver failed because the input matrix is singular.
```
How to solve this problem?

**Comment by talenz** [comment]
SAME PROBLEM. How to solve this?

**Comment by PeterBaelish** [comment]
> Hi, great work! When I tried to quantize my llama model, I met the following error:
> 
> ```
> [2024-11-04 02:04:05 root](train_utils.py 94): INFO ========= Layer 0 =========
> [2024-11-04 02:04:22 root](train_utils.py 164): INFO layer 0 lwc lac iter 0, lr 0.00494542  time 10.204175s, mse: 0.00010393
> [2024-11-04 02:04:31 root](train_utils.py 164): INFO layer 0 lwc lac iter 1, lr 0.00478408  time 8.453322s, mse: 0.00006361
> [2024-11-04 02:04:39 root](train_utils.py 164): INFO layer 0 lwc lac iter 2, lr 0.00452302  time 8.452416s, mse: 0.00004074
> [2024-11-04 02:04:48 root](train_utils.py 164): INFO layer 0 lwc lac iter 3, lr 0.00417365  time 8.596735s, mse: 0.00003601
> [2024-11-04 02:04:56 root](train_utils.py 164): INFO layer 0 lwc lac iter 4, lr 0.00375125  time 8.426240s, mse: 0.00007681
> Traceback (most recent call last):
>   File "/workspace/FlatQuant/./main.py", line 93, in <module>
>     main()
>   File "/workspace/FlatQuant/./main.py", line 35, in main
>     train_utils.cali_flat_quant(args, model, trainloader, utils.DEV, logger=logger)
>   File "/workspace/FlatQuant/flatquant/train_utils.py", line 152, in cali_flat_quant
>     quant_out = layer(fp_inps[index:index+args.cali_bsz,], attention_mask=attention_mask_batch, position_ids=position_ids,cache_position=cache_position)[0]
>   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/modeling_llama.py", line 763, in forward
>     hidden_states, self_attn_weights, present_key_value = self.self_attn(
>   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/workspace/FlatQuant/flatquant/model_tools/llama_utils.py", line 206, in forward
>     query_states, key_states, value_states = self._trans_forward_after_ln(hidden_states)
>   File "/workspace/FlatQuant/flatquant/model_tools/llama_utils.py", line 161, in _trans_forward_after_ln
>     hidden_states = self.ln_trans(hidden_states)
>   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/workspace/FlatQuant/flatquant/trans_utils.py", line 92, in forward
>     matrix_u_left, matrix_u_right = self.linear_u_left.weight, self.linear_u_right.weight
>   File "/usr/local/lib/python3.10/dist-packages/torch/nn/utils/parametrize.py", line 368, in get_parametrized
>     return parametrization()
>   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/torch/nn/utils/parametrize.py", line 265, in forward
>     x = self[0](self.original)
>   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/torch/nn/utils/parametrizations.py", line 90, in forward
>     Q = torch.linalg.solve(torch.add(Id, A, alpha=-0.5), torch.add(Id, A, alpha=0.5))
> torch._C._LinAlgError: torch.linalg.solve: The solver failed because the input matrix is singular.
> ```
> 
> How to solve this problem?

I have encountered same problem, have you solved it yet?

**Comment by rib12316** [comment]
@mxjmtxrm Hello, I encountered the same problem as you did when quantizing the Llama model. May I ask how you managed to solve it?
